apiVersion: v1
kind: Service
metadata:
  name: mongo-svc-green
  labels:
    app: mongo-svc
    env: green
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: mongo
    env: green