apiVersion: batch/v1
kind: Job
metadata:
  name: content-init
  labels:
    env: green
spec:
  template:
    spec:
      containers:
      - name: content-init
        image: team2dnbacr.azurecr.io/hussam-content-init
        env:
          - name: MONGODB_CONNECTION
            value: mongodb://mongo-svc-green:27017/contentdb
      restartPolicy: Never
  backoffLimit: 4