apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-web-deployment-green
  labels:
    app: content-web
    env: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: content-web
      env: green
  template:
    metadata:
      labels:
        app: content-web
        env: green
    spec:
      containers:
      - name: content-web
        image: team2dnbacr.azurecr.io/hussam-content-web-v2:latest
        env:
        - name: CONTENT_API_URL
          value: http://content-api-svc-green:3001
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "1000m"       
        ports:
        - containerPort: 3000