apiVersion: v1
kind: Service
metadata:
  name: content-api-svc-green
  labels:
    app: content-api-svc
    env: green
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  selector:
    app: content-api
    env: green